const fs = require('fs');

const lines = [];

lines.push('<!DOCTYPE html>');
lines.push('<html lang="en">');
lines.push('<head>');
lines.push('<meta charset="utf-8">');
lines.push('<meta name="viewport" content="width=device-width, initial-scale=1">');
lines.push('<title>ABchatbot</title>');
lines.push('<style>');
lines.push('*{margin:0;padding:0;box-sizing:border-box;font-family:Segoe UI,system-ui,sans-serif}');
lines.push(':root{--bg:#0f0f1a;--bg2:#1a1a2e;--bg3:#16213e;--text:#e8e8f0;--text2:#a0a0b8;--text3:#6c6c8a;--accent:#6c63ff;--border:#2a2a4a;--card:#1e1e3a;--success:#22c55e}');
lines.push('body{background:var(--bg);color:var(--text);min-height:100vh}');
lines.push('.app{display:flex;height:100vh;overflow:hidden}');
lines.push('.sidebar{width:260px;background:var(--bg2);border-right:1px solid var(--border);display:flex;flex-direction:column;flex-shrink:0}');
lines.push('.sidebar h2{padding:20px;font-size:20px;background:linear-gradient(135deg,#6c63ff,#4a90d9);-webkit-background-clip:text;-webkit-text-fill-color:transparent;border-bottom:1px solid var(--border)}');
lines.push('.sidebar .new-btn{margin:12px;padding:10px;border-radius:8px;background:var(--accent);color:#fff;border:none;font-size:14px;font-weight:600;cursor:pointer}');
lines.push('.sidebar .new-btn:hover{opacity:.9}');
lines.push('.chat-list{flex:1;overflow-y:auto;padding:8px}');
lines.push('.chat-item{padding:10px 12px;border-radius:8px;cursor:pointer;margin-bottom:2px;font-size:13px}');
lines.push('.chat-item:hover{background:var(--bg3)}');
lines.push('.chat-item.active{background:rgba(108,99,255,.2);border:1px solid var(--accent)}');
lines.push('.chat-item .title{color:var(--text);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}');
lines.push('.chat-item .date{font-size:11px;color:var(--text3);margin-top:3px}');
lines.push('.sidebar-user{padding:12px 16px;border-top:1px solid var(--border);display:flex;align-items:center;justify-content:space-between;font-size:13px}');
lines.push('.main{flex:1;display:flex;flex-direction:column}');
lines.push('.nav{display:flex;gap:4px;padding:0 20px;background:var(--bg2);border-bottom:1px solid var(--border)}');
lines.push('.nav button{padding:10px 16px;font-size:13px;font-weight:500;background:transparent;border:none;color:var(--text2);cursor:pointer;border-bottom:2px solid transparent}');
lines.push('.nav button.active{color:var(--accent);border-bottom-color:var(--accent)}');
lines.push('.nav button:hover{color:var(--text)}');
lines.push('.chat-area{flex:1;display:flex;flex-direction:column}');
lines.push('.chat-header{padding:12px 20px;border-bottom:1px solid var(--border);font-size:14px;font-weight:600;background:var(--bg2)}');
lines.push('.messages{flex:1;overflow-y:auto;padding:20px;display:flex;flex-direction:column;gap:12px}');
lines.push('.msg{display:flex;gap:10px;max-width:80%;animation:fadeIn .3s}');
lines.push('@keyframes fadeIn{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:translateY(0)}}');
lines.push('.msg.user{align-self:flex-end;flex-direction:row-reverse}');
lines.push('.msg-avatar{width:28px;height:28px;border-radius:50%;flex-shrink:0;display:flex;align-items:center;justify-content:center;font-size:12px;font-weight:600}');
lines.push('.msg.user .msg-avatar{background:var(--accent)}');
lines.push('.msg.assistant .msg-avatar{background:#4a90d9}');
lines.push('.msg-bubble{padding:10px 14px;border-radius:12px;font-size:14px;line-height:1.5}');
lines.push('.msg.user .msg-bubble{background:var(--accent);color:#fff;border-bottom-right-radius:4px}');
lines.push('.msg.assistant .msg-bubble{background:var(--card);border:1px solid var(--border);border-bottom-left-radius:4px;color:var(--text)}');
lines.push('.input-area{padding:12px 20px;border-top:1px solid var(--border);background:var(--bg2)}');
lines.push('.model-row{display:flex;gap:6px;margin-bottom:8px;flex-wrap:wrap}');
lines.push('.model-chip{padding:4px 12px;border-radius:16px;font-size:11px;font-weight:500;background:var(--bg);border:1px solid var(--border);color:var(--text2);cursor:pointer}');
lines.push('.model-chip.active{background:var(--accent);color:#fff;border-color:var(--accent)}');
lines.push('.input-row{display:flex;gap:8px}');
lines.push('.input-row input{flex:1;padding:10px 14px;border-radius:10px;background:var(--bg);border:1px solid var(--border);color:var(--text);font-size:14px;outline:none}');
lines.push('.input-row input:focus{border-color:var(--accent)}');
lines.push('.input-row button{width:40px;height:40px;border-radius:50%;background:var(--accent);color:#fff;border:none;font-size:18px;cursor:pointer;flex-shrink:0}');
lines.push('.input-row button:disabled{opacity:.5}');
lines.push('.empty-state{flex:1;display:flex;flex-direction:column;align-items:center;justify-content:center;color:var(--text3);padding:40px;text-align:center}');
lines.push('.empty-state .icon{font-size:48px;margin-bottom:16px;opacity:.5}');
lines.push('.empty-state h3{color:var(--text2);margin-bottom:8px}');
lines.push('.typing{display:flex;gap:3px;padding:4px 0}');
lines.push('.typing span{width:6px;height:6px;background:var(--text3);border-radius:50%;animation:typing 1.4s infinite}');
lines.push('.typing span:nth-child(2){animation-delay:.2s}');
lines.push('.typing span:nth-child(3){animation-delay:.4s}');
lines.push('@keyframes typing{0%,60%,100%{opacity:.3;transform:translateY(0)}30%{opacity:1;transform:translateY(-4px)}}');
lines.push('.media-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(240px,1fr));gap:12px;padding:20px;overflow-y:auto}');
lines.push('.media-card{background:var(--card);border:1px solid var(--border);border-radius:12px;padding:20px;cursor:pointer;transition:all .2s}');
lines.push('.media-card:hover{border-color:var(--accent);transform:translateY(-2px)}');
lines.push('.media-card .icon{font-size:32px;margin-bottom:8px}');
lines.push('.media-card h4{font-size:15px;margin-bottom:4px}');
lines.push('.media-card p{font-size:12px;color:var(--text2)}');
lines.push('.auth-page{min-height:100vh;display:flex;align-items:center;justify-content:center;background:linear-gradient(135deg,#0f0f1a,#16213e);padding:20px}');
lines.push('.auth-card{background:var(--bg2);border:1px solid var(--border);border-radius:16px;padding:32px;width:100%;max-width:400px}');
lines.push('.auth-card h1{font-size:26px;margin-bottom:4px;background:linear-gradient(135deg,#6c63ff,#4a90d9);-webkit-background-clip:text;-webkit-text-fill-color:transparent}');
lines.push('.auth-card p{color:var(--text2);font-size:14px;margin-bottom:20px}');
lines.push('.auth-card label{display:block;font-size:13px;color:var(--text2);margin-bottom:4px}');
lines.push('.auth-card input{width:100%;padding:10px 14px;background:var(--bg);border:1px solid var(--border);border-radius:8px;color:var(--text);font-size:14px;margin-bottom:12px;outline:none}');
lines.push('.auth-card input:focus{border-color:var(--accent)}');
lines.push('.auth-card .btn{width:100%;padding:12px;border-radius:8px;background:var(--accent);color:#fff;border:none;font-size:15px;font-weight:600;cursor:pointer}');
lines.push('.auth-card .btn:hover{opacity:.9}');
lines.push('.auth-card .link{text-align:center;margin-top:16px;font-size:13px;color:var(--text2)}');
lines.push('.auth-card .link a{color:var(--accent);text-decoration:none;cursor:pointer}');
lines.push('.error{color:red;font-size:13px;margin-bottom:12px;padding:8px 12px;background:rgba(255,0,0,.1);border:1px solid rgba(255,0,0,.3);border-radius:8px}');
lines.push('.modal-overlay{position:fixed;top:0;left:0;right:0;bottom:0;background:rgba(0,0,0,.6);display:flex;align-items:center;justify-content:center;z-index:100}');
lines.push('.modal{background:var(--bg2);border:1px solid var(--border);border-radius:16px;padding:24px;width:90%;max-width:480px}');
lines.push('.modal h3{margin-bottom:4px}');
lines.push('.modal p{font-size:13px;color:var(--text2);margin-bottom:16px}');
lines.push('.modal textarea{width:100%;min-height:100px;padding:10px 14px;background:var(--bg);border:1px solid var(--border);border-radius:8px;color:var(--text);font-size:14px;resize:vertical;margin-bottom:16px;outline:none}');
lines.push('.modal textarea:focus{border-color:var(--accent)}');
lines.push('.modal-actions{display:flex;gap:8px;justify-content:flex-end}');
lines.push('.modal-actions button{padding:8px 20px;border-radius:8px;font-size:13px;font-weight:600;cursor:pointer}');
lines.push('.modal-actions .cancel{background:transparent;border:1px solid var(--border);color:var(--text2)}');
lines.push('.modal-actions .generate{background:var(--accent);border:none;color:#fff}');
lines.push('@media(max-width:640px){.sidebar{width:100%;position:fixed;z-index:10}.main{margin-left:0}}');
lines.push('</style>');
lines.push('</head>');
lines.push('<body>');
lines.push('<div id="app"></div>');
lines.push('<script>');

// ----- BROWSER JAVASCRIPT -----
// Use data attributes to avoid inline quoting issues

lines.push('var API="/api";');
lines.push('var state={user:null,token:localStorage.getItem("token"),chats:[],activeChat:null,messages:[],view:"chat",loading:false,mediaForm:null,mediaPrompt:"",selectedModel:"openai/gpt-4o"};');

lines.push('async function api(path,opts){');
lines.push('  opts=opts||{};');
lines.push('  var headers={"Content-Type":"application/json"};');
lines.push('  if(state.token)headers.Authorization="Bearer "+state.token;');
lines.push('  if(opts.headers){Object.assign(headers,opts.headers)}');
lines.push('  try{');
lines.push('    var res=await fetch(API+path,{method:opts.method||"GET",body:opts.body,headers:headers});');
lines.push('    var data=await res.json();');
lines.push('    if(!res.ok&&res.status===401){state.token=null;localStorage.removeItem("token");state.user=null;render();}');
lines.push('    if(!res.ok)throw new Error(data.error||"Request failed");');
lines.push('    return data;');
lines.push('  }catch(e){throw e}');
lines.push('}');

lines.push('function navigate(v){state.view=v;render()}');

lines.push('async function login(e){');
lines.push('  e.preventDefault();');
lines.push('  var fd=new FormData(e.target);');
lines.push('  try{');
lines.push('    var data=await api("/auth/login",{method:"POST",body:JSON.stringify(Object.fromEntries(fd))});');
lines.push('    state.token=data.accessToken;localStorage.setItem("token",data.token||data.accessToken);');
lines.push('    state.user=data.user;render();');
lines.push('  }catch(err){');
lines.push('    var el=document.getElementById("auth-error");if(el){el.style.display="block";el.textContent=err.message}');
lines.push('  }');
lines.push('}');

lines.push('async function register(e){');
lines.push('  e.preventDefault();');
lines.push('  var fd=new FormData(e.target);');
lines.push('  try{');
lines.push('    var data=await api("/auth/register",{method:"POST",body:JSON.stringify(Object.fromEntries(fd))});');
lines.push('    state.token=data.accessToken;localStorage.setItem("token",data.token||data.accessToken);');
lines.push('    state.user=data.user;render();');
lines.push('  }catch(err){');
lines.push('    var el=document.getElementById("auth-error");if(el){el.style.display="block";el.textContent=err.message}');
lines.push('  }');
lines.push('}');

lines.push('function logout(){state.token=null;localStorage.removeItem("token");state.user=null;state.chats=[];state.activeChat=null;render()}');

lines.push('async function loadChats(){');
lines.push('  try{state.chats=await api("/chat");render()}catch(e){}');
lines.push('}');

lines.push('async function newChat(){');
lines.push('  try{');
lines.push('    var chat=await api("/chat",{method:"POST",body:"{}"});');
lines.push('    state.chats.unshift(chat);state.activeChat=chat;state.messages=[];state.view="chat";render();');
lines.push('  }catch(e){}');
lines.push('}');

lines.push('async function selectChatById(id){');
lines.push('  try{');
lines.push('    var data=await api("/chat/"+id);');
lines.push('    state.activeChat=data;state.messages=data.messages||[];state.view="chat";render();');
lines.push('  }catch(e){}');
lines.push('}');

lines.push('async function sendMessage(){');
lines.push('  var input=document.getElementById("msg-input");');
lines.push('  if(!input)return;');
lines.push('  var text=input.value.trim();');
lines.push('  if(!text||state.loading)return;');
lines.push('  input.value="";state.loading=true;');
lines.push('  state.messages.push({role:"user",content:text});render();');
lines.push('  try{');
lines.push('    var chatId=state.activeChat._id||state.activeChat.id;');
lines.push('    var res=await api("/chat/"+chatId+"/message",{method:"POST",body:JSON.stringify({content:text,model:state.selectedModel})});');
lines.push('    state.messages.push({role:"assistant",content:res.reply});state.loading=false;');
lines.push('    if(state.activeChat.title==="New Chat"){state.activeChat.title=text.substring(0,60);loadChats()}');
lines.push('    render();');
lines.push('  }catch(e){');
lines.push('    state.messages.push({role:"assistant",content:"Error: "+e.message});state.loading=false;render();');
lines.push('  }');
lines.push('}');

lines.push('function escapeHtml(s){s=s||"";var d=document.createElement("div");d.textContent=s;return d.innerHTML}');

// App() function - main layout
lines.push('function App(){');
lines.push('  if(!state.user)return AuthPage();');
lines.push('  document.title="ABchatbot - "+state.user.name;');
lines.push('  var h="";');
lines.push('  h+="<div class=\\"app\\">";');
lines.push('  h+="<aside class=\\"sidebar\\">";');
lines.push('  h+="<h2>&#10022; ABchatbot</h2>";');
lines.push('  h+="<button class=\\"new-btn\\" onclick=\\"newChat()\\">+ New Chat</button>";');
lines.push('  h+="<div class=\\"chat-list\\">";');
lines.push('  for(var i=0;i<state.chats.length;i++){');
lines.push('    var c=state.chats[i];');
lines.push('    var cid=c._id||c.id;');
lines.push('    var active=(state.activeChat&&(state.activeChat._id||state.activeChat.id))===cid?" active":"";');
lines.push('    h+="<div class=\\"chat-item"+active+"\\" data-id=\\""+cid+"\\" onclick=\\"selectChatById(this.dataset.id)\\">";');
lines.push('    h+="<div class=\\"title\\">"+escapeHtml(c.title)+"</div>";');
lines.push('    h+="<div class=\\"date\\">"+new Date(c.updatedAt).toLocaleDateString()+"</div>";');
lines.push('    h+="</div>";');
lines.push('  }');
lines.push('  h+="</div>";');
lines.push('  h+="<div class=\\"sidebar-user\\">";');
lines.push('  h+="<span>&#128100; "+escapeHtml(state.user.name)+"</span>";');
lines.push('  h+="<button style=\\"background:none;border:none;color:#6c6c8a;cursor:pointer;font-size:12px\\" onclick=\\"logout()\\">Sign out</button>";');
lines.push('  h+="</div>";');
lines.push('  h+="</aside>";');
lines.push('  h+="<div class=\\"main\\">";');
lines.push('  h+="<nav class=\\"nav\\">";');
lines.push('  h+="<button class=\\""+(state.view==="chat"?"active":"")+"\\" onclick=\\"navigate(\\'chat\\')\\">Chat</button>";');
lines.push('  h+="<button class=\\""+(state.view==="media"?"active":"")+"\\" onclick=\\"navigate(\\'media\\')\\">Create</button>";');
lines.push('  h+="</nav>";');
lines.push('  h+=state.view==="chat"?ChatView():MediaView();');
lines.push('  h+="</div>";');
lines.push('  h+="</div>";');
lines.push('  return h;');
lines.push('}');

// AuthPage()
lines.push('function AuthPage(){');
lines.push('  var isLogin=location.hash!=="#register";');
lines.push('  var h="";');
lines.push('  h+="<div class=\\"auth-page\\">";');
lines.push('  h+="<div class=\\"auth-card\\">";');
lines.push('  h+="<h1>"+(isLogin?"Welcome Back":"Create Account")+"</h1>";');
lines.push('  h+="<p>"+(isLogin?"Sign in to ABchatbot":"Get started with ABchatbot")+"</p>";');
lines.push('  h+="<div id=\\"auth-error\\" style=\\"display:none;color:red;font-size:13px;margin-bottom:12px;padding:8px 12px;background:rgba(255,0,0,.1);border:1px solid rgba(255,0,0,.3);border-radius:8px\\"></div>";');
lines.push('  h+="<form onsubmit=\\""+(isLogin?"login(event)":"register(event))+"\\">";');
lines.push('  if(!isLogin)h+="<label>Name</label><input name=\\"name\\" placeholder=\\"John Doe\\" required>";');
lines.push('  h+="<label>Email</label><input name=\\"email\\" type=\\"email\\" placeholder=\\"you@example.com\\" required>";');
lines.push('  h+="<label>Password</label><input name=\\"password\\" type=\\"password\\" placeholder=\\"Min 6 chars\\" required>";');
lines.push('  h+="<button class=\\"btn\\" type=\\"submit\\">"+(isLogin?"Sign In":"Create Account")+"</button>";');
lines.push('  h+="</form>";');
lines.push('  h+="<div class=\\"link\\" style=\\"text-align:center;margin-top:16px;font-size:13px;color:#a0a0b8\\">";');
lines.push('  if(isLogin){h+="Don\\'t have an account? <a href=\\"#register\\" style=\\"color:#6c63ff\\">Register</a>"}');
lines.push('  else{h+="Already have an account? <a href=\\"#\\" style=\\"color:#6c63ff\\">Sign in</a>"}');
lines.push('  h+="</div>";');
lines.push('  h+="</div>";');
lines.push('  h+="</div>";');
lines.push('  return h;');
lines.push('}');

// ChatView()
lines.push('function ChatView(){');
lines.push('  if(!state.activeChat){');
lines.push('    return "<div class=\\"empty-state\\" style=\\"flex:1;display:flex;flex-direction:column;align-items:center;justify-content:center;color:#6c6c8a;padding:40px;text-align:center\\"><div style=\\"font-size:48px;margin-bottom:16px;opacity:.5\\">&#128172;</div><h3 style=\\"color:#a0a0b8;margin-bottom:8px\\">Start a conversation</h3><p style=\\"font-size:13px\\">Create a new chat or select one to begin.</p></div>";');
lines.push('  }');
lines.push('  var h="";');
lines.push('  h+="<div class=\\"chat-area\\" style=\\"flex:1;display:flex;flex-direction:column\\">";');
lines.push('  h+="<div class=\\"chat-header\\" style=\\"padding:12px 20px;border-bottom:1px solid #2a2a4a;font-size:14px;font-weight:600;background:#1a1a2e\\">"+escapeHtml(state.activeChat.title)+"</div>";');
lines.push('  h+="<div class=\\"messages\\" id=\\"msg-area\\" style=\\"flex:1;overflow-y:auto;padding:20px;display:flex;flex-direction:column;gap:12px\\">";');
lines.push('  if(state.messages.length===0){');
lines.push('    h+="<div class=\\"empty-state\\" style=\\"flex:1;display:flex;flex-direction:column;align-items:center;justify-content:center;color:#6c6c8a;padding:40px;text-align:center\\"><div style=\\"font-size:48px;margin-bottom:16px;opacity:.5\\">&#10024;</div><h3 style=\\"color:#a0a0b8;margin-bottom:8px\\">Ask anything</h3><p style=\\"font-size:13px\\">Questions, ideas, content - I am here to help.</p></div>";');
lines.push('  }else{');
lines.push('    for(var i=0;i<state.messages.length;i++){');
lines.push('      var m=state.messages[i];');
lines.push('      var isUser=m.role==="user";');
lines.push('      h+="<div class=\\"msg\\" style=\\"display:flex;gap:10px;max-width:80%;animation:fadeIn .3s;align-self:"+(isUser?"flex-end":"flex-start")+";flex-direction:"+(isUser?"row-reverse":"row")+"\\">";');
lines.push('      h+="<div style=\\"width:28px;height:28px;border-radius:50%;flex-shrink:0;display:flex;align-items:center;justify-content:center;font-size:12px;font-weight:600;background:"+(isUser?"#6c63ff":"#4a90d9")+"\\">"+(isUser?"U":"AI")+"</div>";');
lines.push('      h+="<div style=\\"padding:10px 14px;border-radius:12px;font-size:14px;line-height:1.5;background:"+(isUser?"#6c63ff":"#1e1e3a")+";color:#fff\\">"+escapeHtml(m.content).replace(/\\n/g,"<br>")+"</div>";');
lines.push('      h+="</div>";');
lines.push('    }');
lines.push('  }');
lines.push('  if(state.loading){');
lines.push('    h+="<div class=\\"msg\\" style=\\"display:flex;gap:10px;max-width:80%\\"><div style=\\"width:28px;height:28px;border-radius:50%;flex-shrink:0;display:flex;align-items:center;justify-content:center;font-size:12px;font-weight:600;background:#4a90d9\\">AI</div><div style=\\"padding:10px 14px;border-radius:12px;font-size:14px;background:#1e1e3a;border:1px solid #2a2a4a\\"><div class=\\"typing\\" style=\\"display:flex;gap:3px\\"><span style=\\"width:6px;height:6px;background:#6c6c8a;border-radius:50%;animation:typing 1.4s infinite\\"></span><span style=\\"width:6px;height:6px;background:#6c6c8a;border-radius:50%;animation:typing 1.4s infinite;animation-delay:.2s\\"></span><span style=\\"width:6px;height:6px;background:#6c6c8a;border-radius:50%;animation:typing 1.4s infinite;animation-delay:.4s\\"></span></div></div></div>";');
lines.push('  }');
lines.push('  h+="</div>";');
lines.push('  h+="<div style=\\"padding:12px 20px;border-top:1px solid #2a2a4a;background:#1a1a2e\\">";');
lines.push('  h+="<div style=\\"display:flex;gap:6px;margin-bottom:8px;flex-wrap:wrap\\">";');
lines.push('  var models=[["GPT-4o","openai/gpt-4o"],["Claude","anthropic/claude-3.5-sonnet"],["Gemini","google/gemini-pro-1.5"],["Llama","meta-llama/llama-3.1-8b-instruct"]];');
lines.push('  for(var j=0;j<models.length;j++){');
lines.push('    var active=state.selectedModel===models[j][1]?"background:#6c63ff;color:#fff;border-color:#6c63ff":"";');
lines.push('    h+="<span style=\\"padding:4px 12px;border-radius:16px;font-size:11px;font-weight:500;background:#0f0f1a;border:1px solid #2a2a4a;color:#a0a0b8;cursor:pointer;'+active+'\\" onclick=\\"state.selectedModel=\\'"+models[j][1]+"\\';render()\\">"+models[j][0]+"</span>";');
lines.push('  }');
lines.push('  h+="</div>";');
lines.push('  h+="<div style=\\"display:flex;gap:8px\\">";');
lines.push('  h+="<input id=\\"msg-input\\" style=\\"flex:1;padding:10px 14px;border-radius:10px;background:#0f0f1a;border:1px solid #2a2a4a;color:#e8e8f0;font-size:14px;outline:none\\" placeholder=\\"Ask anything...\\" onkeydown=\\"if(event.key===\'Enter\'&&!event.shiftKey){event.preventDefault();sendMessage()}\\">";');
lines.push('  h+="<button style=\\"width:40px;height:40px;border-radius:50%;background:#6c63ff;color:#fff;border:none;font-size:18px;cursor:pointer;flex-shrink:0;opacity:"+(state.loading?".5":"1")+"\\" onclick=\\"sendMessage()\\" id=\\"send-btn\\">&#10148;</button>";');
lines.push('  h+="</div>";');
lines.push('  h+="</div>";');
lines.push('  h+="</div>";');
lines.push('  return h;');
lines.push('}');

// MediaView()
lines.push('function MediaView(){');
lines.push('  var types=[');
lines.push('    {type:"image",icon:"&#128248;",title:"Image & Flyer Generator",desc:"Create stunning flyers, posters, social media graphics"},');
lines.push('    {type:"document",icon:"&#128196;",title:"Document Creator",desc:"Generate reports, articles, presentations"},');
lines.push('    {type:"video",icon:"&#127916;",title:"Video Script Writer",desc:"Create professional video scripts and storyboards"},');
lines.push('    {type:"audio",icon:"&#127926;",title:"Audio & Speech",desc:"Generate voiceovers, podcast scripts, narration"}');
lines.push('  ];');
lines.push('  var epMap={image:"image",document:"document",video:"video",audio:"document"};');
lines.push('  var h="";');
lines.push('  h+="<div style=\\"overflow-y:auto;flex:1\\">";');
lines.push('  h+="<div style=\\"padding:20px 20px 0\\">";');
lines.push('  h+="<h2>Create with AI</h2>";');
lines.push('  h+="<p style=\\"color:#a0a0b8;font-size:13px;margin-top:4px\\">Generate flyers, posters, documents, video scripts, and more</p>";');
lines.push('  h+="</div>";');
lines.push('  if(state.mediaForm){');
lines.push('    h+="<div class=\\"modal-overlay\\" style=\\"position:fixed;top:0;left:0;right:0;bottom:0;background:rgba(0,0,0,.6);display:flex;align-items:center;justify-content:center;z-index:100\\" onclick=\\"state.mediaForm=null;render()\\">";');
lines.push('    h+="<div style=\\"background:#1a1a2e;border:1px solid #2a2a4a;border-radius:16px;padding:24px;width:90%;max-width:480px\\" onclick=\\"event.stopPropagation()\\">";');
lines.push('    h+="<h3>Generate "+escapeHtml(state.mediaForm.title)+"</h3>";');
lines.push('    h+="<p style=\\"font-size:13px;color:#a0a0b8;margin-bottom:16px\\">Describe what you want to create in detail</p>";');
lines.push('    h+="<textarea style=\\"width:100%;min-height:100px;padding:10px 14px;background:#0f0f1a;border:1px solid #2a2a4a;border-radius:8px;color:#e8e8f0;font-size:14px;resize:vertical;margin-bottom:16px;outline:none\\" placeholder=\\"Describe your "+escapeHtml(state.mediaForm.type)+"...\\" oninput=\\"state.mediaPrompt=this.value\\">"+escapeHtml(state.mediaPrompt)+"</textarea>";');
lines.push('    h+="<div style=\\"display:flex;gap:8px;justify-content:flex-end\\">";');
lines.push('    h+="<button style=\\"padding:8px 20px;border-radius:8px;font-size:13px;font-weight:600;cursor:pointer;background:transparent;border:1px solid #2a2a4a;color:#a0a0b8\\" onclick=\\"state.mediaForm=null;render()\\">Cancel</button>";');
lines.push('    h+="<button style=\\"padding:8px 20px;border-radius:8px;font-size:13px;font-weight:600;cursor:pointer;background:#6c63ff;border:none;color:#fff\\" onclick=\\"generateMedia(\\'"+state.mediaForm.type+"\\',\\'"+epMap[state.mediaForm.type]+"\\')\\">Generate</button>";');
lines.push('    h+="</div>";');
lines.push('    h+="</div>";');
lines.push('    h+="</div>";');
lines.push('  }');
lines.push('  h+="<div style=\\"display:grid;grid-template-columns:repeat(auto-fill,minmax(240px,1fr));gap:12px;padding:20px\\">";');
lines.push('  for(var i=0;i<types.length;i++){');
lines.push('    var t=types[i];');
lines.push('    h+="<div style=\\"background:#1e1e3a;border:1px solid #2a2a4a;border-radius:12px;padding:20px;cursor:pointer;transition:all .2s\\" onclick=\\"state.mediaForm={type:\\'"+t.type+"\\',title:\\'"+escapeHtml(t.title)+"\\',desc:\\'"+escapeHtml(t.desc)+"\\'};state.mediaPrompt=\\'\\';render()\\">";');
lines.push('    h+="<div style=\\"font-size:32px;margin-bottom:8px\\">"+t.icon+"</div>";');
lines.push('    h+="<h4>"+escapeHtml(t.title)+"</h4>";');
lines.push('    h+="<p style=\\"font-size:12px;color:#a0a0b8\\">"+escapeHtml(t.desc)+"</p>";');
lines.push('    h+="</div>";');
lines.push('  }');
lines.push('  h+="</div>";');
lines.push('  h+="</div>";');
lines.push('  return h;');
lines.push('}');

lines.push('function render(){');
lines.push('  document.getElementById("app").innerHTML=App();');
lines.push('  if(state.view==="chat"){');
lines.push('    setTimeout(function(){var a=document.getElementById("msg-area");if(a)a.scrollTop=a.scrollHeight},50)');
lines.push('  }');
lines.push('}');

lines.push('(async function(){');
lines.push('  if(state.token){');
lines.push('    try{var d=await api("/auth/profile");state.user=d.user;await loadChats()}catch(e){state.token=null;localStorage.removeItem("token")}');
lines.push('  }');
lines.push('  render();');
lines.push('  window.addEventListener("hashchange",render)');
lines.push('})();');

lines.push('</script>');
lines.push('</body>');
lines.push('</html>');

const html = lines.join('\n');
fs.writeFileSync('ABchatbot/standalone/app.html', html);
console.log('Generated app.html - length:', html.length);
console.log('Has App():', html.includes('function App()'));
console.log('Has sendMessage:', html.includes('async function sendMessage'));
